# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat
  pod 'VonageClientSDKChat', '1.2.0-alpha.11'
end
